FROM node:22-alpine

WORKDIR /inkeep-agents

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY turbo.json drizzle.config.ts ./

COPY apps/ ./apps/

RUN npm install -g pnpm@10.17.0

RUN pnpm install --frozen-lockfile

EXPOSE 3000

CMD ["pnpm", "dev:ui", "--host", "0.0.0.0"]